## Import Modules

In [1]:
import torch
import numpy as np

## Tensors
A tensor is a number, vector, matrix or any n-dimensional array.

In [2]:
# Single type tensor
t1 = torch.tensor(4.)
print(t1.shape)
print(t1.dtype)

torch.Size([])
torch.float32


In [3]:
# Vector
t2 = torch.tensor([1., 2, 3, 4])
print(t2.shape)
print(t2.dtype)

torch.Size([4])
torch.float32


In [4]:
# Matrix
t3 = torch.tensor([[5., 6],
                   [7, 8],
                   [9, 10]])
print(t3.shape)
print(t3.dtype)

torch.Size([3, 2])
torch.float32


In [5]:
# 3-dimensional array
t4 = torch.tensor([
    [[11, 12, 13],
     [13, 14, 15]],
    [[15, 16, 17],
     [17, 18, 19.]]])
print(t4.shape)
print(t4.dtype)

torch.Size([2, 2, 3])
torch.float32


## Tensor operations and gradients

In [6]:
# Create tensor
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
                    # requires_grad parameter
                    # enable the autograd feature

# Arithmetic operations
y = w * x + b

# Compute derivatives
y.backward()

# Display gradients
print("dy/dx:", x.grad)
print("dy/dw:", w.grad)
print("dy/db:", b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


## Tensor function

In [7]:
# Create a tensor with a fixed value for every element
t5 = torch.full((3, 2), 42)
t5

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [8]:
# Concatenate two tensors with compatible shapes
t6 = torch.cat((t3, t5))
t6

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])

In [9]:
# Compute the sin of each element
t7 = torch.sin(t6)
t7

tensor([[-0.9589, -0.2794],
        [ 0.6570,  0.9894],
        [ 0.4121, -0.5440],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

In [10]:
t8 = t7.reshape(3, 2, 2)
t8

tensor([[[-0.9589, -0.2794],
         [ 0.6570,  0.9894]],

        [[ 0.4121, -0.5440],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])

## PyTorch with NumPy

In [11]:
x = np.array([[1, 2], [3, 4.]])
x

array([[1., 2.],
       [3., 4.]])

In [12]:
# Convert the numpy array to a torch tensor.
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [13]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

In [14]:
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])